--@AUTOR(ES):       GUTIÉRREZ CASTILLO OSCAR, VALDERRAMA NAVARRO ARMANDO
--@FECHA CREACIÓN:  01/12/2018
--@DESCRIPCIÓN:     CREACION Y ASIGNACION DE USUARIOS


--CREAMOS USUARIO ADMINISTRDOR


--CREAMOS EL USUARIO VAGU_PROY_ADMIN
CREATE USER VAGU_PROY_ADMIN IDENTIFIED BY VAGUPA
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;

--CREAMOS EL ROL ADMINISTADOR CON LOS PERMINOS NECESARIOS PARA ADMINISTRAR

GRANT 	CREATE SESSION	 TO VAGU_PROY_ADMIN;
CREATE ROLE ROL_ADMIN;

-- ASIGNAMOS AL ROL PERMISOS
GRANT 
	CREATE TABLE
	,CREATE VIEW
	,CREATE SYNONYM
	,CREATE PUBLIC SYNONYM
	,CREATE SEQUENCE
	,CREATE TRIGGER
	,CREATE PROCEDURE
TO VAGU_PROY_ADMIN;

GRANT ROL_ADMIN TO VAGU_PROY_ADMIN

--CREAMOS AL USUARIO INVITADO 

--CREAMOS EL USUARIO VAGU_PROY_INVITADO
CREATE USER VAGU_PROY_INVITADO IDENTIFIED BY VAGUPI
DEFAULT  TABLESPACE USERS
QUOTA 0M ON USERS;

GRANT 	CREATE SESSION TO  VAGU_PROY_INVITADO;
--CREAMOS EL ROL INVITADO
CREATE ROLE ROL_INVITADO;

-- ASIGNAMOS AL ROL PERMISOS
GRANT 
	CREATE SESSION
TO ROL_INVITADO;

GRANT ROL_INVITADO TO VAGU_PROY_INVITADO;