--@Autor(es): Gutiérrez Castillo Oscar, Valderrama Navarro Armando
--@Fecha creación: 01/12/2018
--@Descripción:  Creacion de tablas y secuencias


CREATE TABLE CARRERA( --CATALOGO DE CARRERAS
  CARRERA_ID  NUMBER(2,0)   NOT NULL,
  NOMBRE      VARCHAR2(50)  NOT NULL, 
  CLAVE       NUMBER(3,0)   NOT NULL,
  DESCRIPCION VARCHAR2(150) NOT NULL,
  CONSTRAINT PK_CARRERA PRIMARY KEY (CARRERA_ID)
)
;

CREATE TABLE PLAN_ESTUDIOS( --CATALOGO DE PLAN DE ESTUDIOS
  PLAN_ESTUDIOS_ID  NUMBER(4,0) NOT NULL,
  CLAVE             VARCHAR2(7) NOT NULL,
  FECHA_APROVACION  DATE        NOT NULL,
  FECHA_TERMINO     DATE        NULL,--Solo si ya remplazo el plan de esutdios
  CONSTRAINT PK_PLAN_ESTUDIOS PRIMARY KEY (PLAN_ESTUDIOS_ID)
)
;

CREATE TABLE ASIGNATURA( --CATALOGO DE ASIGNATURAS
  ASIGNATURA_ID     NUMBER(4,0)   NOT NULL,
  CLAVE             NUMBER(4,0)   NOT NULL,
  NOMBRE            VARCHAR2(50)  NOT NULL,
  SEMESTRE_CURSAR   NUMBER(2)     NOT NULL,
  CREDITOS          NUMBER(2,0)   NOT NULL,
  PLAN_ESTUDIOS_ID  NUMBER(4,0)   NOT NULL,
  --------Reservado a materias que sean de una carrera en particular--------
  ASIGNATURA_ANTECEDENTE  NUMBER(4,0) NULL, 
  SEMESTRE_IMPARTICION  NUMBER(2) NULL,
  --------Reservado a materias que sean de una carrera en particular--------
  CONSTRAINT PK_ASIGNATURA PRIMARY KEY (ASIGNATURA_ID),
  CONSTRAINT FK_ASIGNATURA_ANTECEDENTE FOREIGN KEY (ASIGNATURA_ANTECEDENTE)
  REFERENCES ASIGNATURA(ASIGNATURA_ID)
)
;

CREATE TABLE DIA_SEMANA( --CATALOGO DIAS DE LA SEMANA
  DIA_SEMANA_ID NUMBER(6)   NOT NULL,
  DESCRIPCION   VARCHAR2(10)  NOT NULL,
  CONSTRAINT PK_DIA_SEMANA PRIMARY KEY (DIA_SEMANA_ID)
  CONSTRAINT CHK_DIA_SEMANA_ID
  CHECK (DIA_SEMANA_ID BETWEEN 1 and 6) --Lunes a sábado
)
;

CREATE TABLE HORARIO( --CATALOGO DE HORARIOS (DEPENDE DE DIA_SEMANA)
  HORARIO_ID      NUMBER(5,0) NOT NULL,
  DIA_IMPARTICION NUMBER(1)   NOT NULL,
  NUMERO_SALON    VARCHAR2(4) NOT NULL,
  NUMERO_CLASE    NUMBER(5)   NOT NULL,
  HORA_INICIO     DATE        NOT NULL,
  HORA_FIN        DATE          NOT NULL,
  CONSTRAINT PK_HORARIO PRIMARY KEY (HORARIO_ID),
  CONSTRAINT FK_DIA_IMPARTICION FOREIGN KEY (NUMERO_CLASE)
  REFERENCES DIA_SEMANA(DIA_SEMANA_ID)
  CONSTRAINT CHK_NUMERO_CLASE
  CHECK (NUMERO_CLASE BETWEEN 1 and 5)
)
;

CREATE TABLE SEMESTRE( --Catalogo de semstre
  SEMESTRE_ID NUMBER(3) NOT NULL,
  ANIO        NUMBER(4) NOT NULL,
  PERIODO     NUMBER(1) NOT NULL,
  CONSTRAINT PK_SEMESTRE PRIMARY KEY (SEMESTRE_ID)
)
;

CREATE TABLE GRADO_ESTUDIOS( --Catalogo de grados de estudios
  GRADO_ESTUDIOS_ID NUMBER(1,0)   NOT NULL,
  CLAVE             VARCHAR2(2)   NOT NULL,
  DESCRIPCION       VARCHAR2(12)  NOT NULL,
  CONSTRAINT PK_GRADO_ESTUDIOS PRIMARY KEY (GRADO_ESTUDIOS)
)
;

CREATE TABLE PUESTO(
  PUESTO_ID     NUMBER(3,0)   NOT NULL,
  CLAVE         VARCHAR2(2)   NOT NULL,
  DESCRIPCION   VARCHAR2(12)  NOT NULL,
  CONSTRAINT PK_PUESTO PRIMARY KEY (PUESTO_ID)

)
;

CREATE TABLE STATUS_TESIS( --CATALOGO DE ESTATUS DE TESIS
  STATUS_TESIS_ID NUMBER(1,0)   NOT NULL,
  CLAVE           VARCHAR2(15)  NOT NULL,
  DESCRIPCION     VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_STATUS_TESIS PRIMARY KEY (STATUS_TESIS_ID)
)
;

CREATE TABLE PROFESOR( --PROFESORES
  PROFESOR_ID NUMBER(6,0)   NOT NULL,
  NOMBRE      VARCHAR2(50)  NOT NULL,
  AP_PATERNO  VARCHAR2(50)  NOT NULL,
  AP_MATERNO  VARCHAR2(50)  NULL,
  RFC         VARCHAR2(13)  NOT NULL,
  CEDULA_PROFESIONAL  NUMBER(7,0)   NOT NULL,
  GRADO_ESTUDIOS_ID NUMBER(1,0)   NOT NULL,
  CONSTRAINT PK_PROFESOR PRIMARY KEY (PROFESOR_ID),
  CONSTRAINT FK_GRADO_ESTUDIOS FOREIGN KEY (GRADO_ESTUDIOS_ID)
  REFERENCES GRADO_ESTUDIOS(GRADO_ESTUDIOS_ID)
)
;

CREATE TABLE ESTUDIANTE( --ESTUDIANTES
  ESTUDIANTE_ID       NUMBER(6,0) NOT NULL,
  NOMBRE              VARCHAR2(50) NOT NULL,
  AP_PATERNO          VARCHAR2(50) NOT NULL,
  AP_MATERNO          VARCHAR2(50) NULL,
  FECHA_NACIMIENTO    DATE NOT NULL,
  NUMERO_CUENTA       NUMBER(10) NOT NULL,
  CEDULA_PROFESIONAL  NUMBER(7,0) NULL, --Se asigna cuando la tesis del estudiante pasa al estado CON_CEDULA
  TESIS_ID            NUMBER(4,0) NULL, 
  CARRERA_ID          NUMBER(2,0)   NOT NULL,
  PLAN_ESTUDIOS_ID    NUMBER(4,0) NOT NULL,
  CONSTRAINT PK_ESTUDIANTE PRIMARY KEY (ESTUDIANTE_ID),
  CONSTRAINT FK_CARRERA_ID FOREIGN KEY (CARRERA_ID)
  REFERENCES CARRERA(CARRERA_ID),
  CONSTRAINT FK_PLAN_ESTUDIOS_ID FOREIGN KEY (PLAN_ESTUDIOS_ID)
  REFERENCES PLAN_ESTUDIOS(PLAN_ESTUDIOS_ID),
  CONSTRAINT FK_TESIS_ID FOREIGN KEY (TESIS_ID)
  REFERENCES TESIS(TESIS_ID)
)
;

CREATE TABLE CURSO(
  CURSO_ID      NUMBER(10,0)  NOT NULL,
  ASIGNATURA_ID NUMBER(4,0)   NOT NULL,
  SEMESTRE_ID   NUMBER(3)     NOT NULL,
  PROFESOR_ID   NUMBER(6,0)   DEFAULT 0, --En caso de no asignar profesor, se asigna 0
  NUM_GRUPO     NUMBER(4)     NOT NULL,
  HORARIO_ID    NUMBER(5,0)   NOT NULL,
  CONSTRAINT PK_CURSO PRIMARY KEY (CURSO_ID),
  CONSTRAINT FK_ASIGNATURA_ID FOREIGN KEY (ASIGNATURA_ID)
  REFERENCES ASIGNATURA(ASIGNATURA_ID),
  CONSTRAINT FK_ASIGNATURA_ID FOREIGN KEY (SEMESTRE_ID)
  REFERENCES SEMESTRE(SEMESTRE_ID),
  CONSTRAINT FK_ASIGNATURA_ID FOREIGN KEY (PROFESOR_ID)
  REFERENCES PROFESOR(PROFESOR_ID),
  CONSTRAINT FK_ASIGNATURA_ID FOREIGN KEY (HORARIO_ID)
  REFERENCES HORARIO(HORARIO_ID)
)
;

CREATE TABLE ESTUDIANTE_INSCRITO_ID(
  ESTUDIANTE_INSCRITO_ID  NUMBER(10, 0) NOT NULL,
  CURSO_ID                NUMBER(10, 0) NOT NULL,
  ESTUDIANTE_ID           NUMBER(6, 0)  NOT NULL,
  CALIFICACION            NUMBER(2, 0)  NULL, --Se actualiza al finalizar el semestre
  NUM_INSCRIPCION         NUMBER(4,0)   NOT NULL,
  CONSTRAINT PK_ESTUDIANTE_INSCRITO PRIMARY KEY (ESTUDIANTE_INSCRITO_ID), 
  CONSTRAINT FK_CURSO FOREIGN KEY (CURSO_ID)
  REFERENCES CURSO(CURSO_ID),
  CONSTRAINT FK_ESTUDIANTE FOREIGN KEY (ESTUDIANTE_ID)
  REFERENCES ESTUDIANTE(ESTUDIANTE_ID)
)
;

CREATE TABLE PROFESOR_ASIGNATURA(
  PROFESOR_ID             NUMBER(6,0)   NOT NULL,
  NUM_CONTRATO            NUMBER(10,0)  NOT NULL,
  FECHA_INICIO_CONTRATO   DATE          NOT NULL,
  FECHA_FIN_CONTRATO      DATE          NOT NULL,
  NUM_VECES_SINODAL       NUMBER(3)     NOT NULL,
  ES_PROFESOR_ASIGNATURA  CHAR(1)       NULL,
  ES_PROFESOR_CARRERA     CHAR(1)       NULL, 
  ES_PROFESOR_ADMINISTRADOR CHAR(1)     NULL,
  CONSTRAINT PK_PROFESOR_ASIGNATURA PRIMARY KEY PROFESOR_ID,
  CONSTRAINT FK_PROFESOR FOREIGN KEY (PROFESOR_ID)
  REFERENCES PROFESOR(PROFESOR_ID)
)
;

CREATE TABLE PROFESOR_CARRERA(
  PROFESOR_ID   NUMBER(6,0) NOT NULL,
  CONSTRAINT PK_PROFESOR_CARRERA PRIMARY KEY PROFESOR_ID,
  CONSTRAINT FK_PROFESOR FOREIGN KEY (PROFESOR_ID)
  REFERENCES PROFESOR(PROFESOR_ID)
)
;

CREATE TABLE PROFESOR_ADMINISTRADOR(
  PROFESOR_ID   NUMBER(6,0) NOT NULL,
  PUESTO_ID     NUMBER(3,0) NOT NULL,
  CONSTRAINT PK_PROFESOR_CARRERA PRIMARY KEY PROFESOR_ID,
  CONSTRAINT FK_PROFESOR FOREIGN KEY (PROFESOR_ID)
  REFERENCES PROFESOR(PROFESOR_ID),
  CONSTRAINT PK_PUESTO FOREIGN KEY (PUESTO_ID)
  REFERENCES PUETO(PUESTO_ID)
)
;

CREATE TABLE ESPECIALIDAD(
  ESPECIALIDAD_ID   NUMBER(3,0)   NOT NULL,
  PROFESOR_ID       NUMBER(6,0)   NOT NULL,
  GRADO_ESTUDIOS_ID NUMBER(1,0)   NOT NULL,
  CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY (ESPECIALIDAD_ID),
  CONSTRAINT FK_GRADO_ESTUDIOS FOREIGN KEY (GRADO_ESTUDIOS_ID)
  REFERENCES GRADO_ESTUDIOS(GRADO_ESTUDIOS_ID)
)
;

CREATE TABLE TESIS(
  TESIS_ID          NUMBER(4,0)   NOT NULL,
  NOMBRE            VARCHAR2(50)  NOT NULL,
  FECHA_REGISTRO    DATE          NOT NULL,
  OBJETIVO          VARCHAR2(150) NOT NULL,
  PDF               BLOB          NULL,--Lo resolverá el script s-17
  STATUS_TESIS_ID   NUMBER(1,0)   NOT NULL,     
  DIRECTOR_TESIS_ID NUMBER(6,0)   NULL,--Se asigna posterior a ser aceptada la tesis
  CONSTRAINT PK_TESIS PRIMARY KEY (TESIS_ID),
  CONSTRAINT FK_STATUS_TESIS FOREIGN KEY (STATUS_TESIS_ID)
  REFERENCES STATUS_TESIS(STATUS_TESIS_ID),
  CONSTRAINT FK_ASIGNATURA_ID FOREIGN KEY (DIRECTOR_TESIS_ID)
  REFERENCES PROFESOR(PROFESOR_ID)
)
;

CREATE TABLE TESIS_HISTORICO(
  TESIS_HISTORICO_ID  NUMBER(8,0) NOT NULL,
  STATUS_TESIS_ID     NUMBER(1,0) NOT NULL,     
  TESIS_ID            NUMBER(4,0) NOT NULL,
  FECHA_MODIFICAICON  DATE        NOT NULL,
  CONSTRAINT PK_TESIS_HISTORICO PRIMARY KEY (TESIS_HISTORICO_ID),
  CONSTRAINT FK_STATUS_TESIS FOREIGN KEY (STATUS_TESIS_ID)
  REFERENCES STATUS_TESIS(STATUS_TESIS_ID),
  CONSTRAINT FK_TESIS FOREIGN KEY (TESIS_ID)
  REFERENCES TESIS(TESIS_ID)  
)
;

CREATE TABLE PLAN_ESTUDIOS_CARRERA(
  PLAN_ESTUDIOS_CARRERA_ID 
  CARRERA_ID        NUMBER(2,0) NOT NULL,
  PLAN_ESTUDIOS_ID  NUMBER(4,0) NOT NULL,

)
;


CREATE TABLE CARRERA_ASIGNATURA(
  CARRERA_ASIGNATURA_ID
  CARRERA_ID    NUMBER(2,0) NOT NULL,
  ASIGNATURA_ID NUMBER(4,0) NOT NULL,
)
;

CREATE TABLE CURSO_HORARIO(
  CURSO_HORARIO_ID
  CURSO_ID    NUMBER(10,0)NOT NULL,
  HORARIO_ID    NUMBER(5,0) NOT NULL,
)
;


CREATE TABLE INSCRIPCION_CURSO(
    ESTUDIANTE_INSCRITO_ID    NUMBER(10, 0) NOT NULL,
  CURSO_ID    NUMBER(10,0)NOT NULL,

)
;

CREATE TABLE HISTORICO_STATUS_TESIS(
  TESIS_HISTORICO_ID  NUMBER(8,0)   NOT NULL,
  STATUS_TESIS_ID NUMBER(1,0)   NOT NULL,

)
;

CREATE TABLE TESIS_SINODAL(
  TESIS_SINODAL_ID
  TESIS_ID
  SINODAL_ID
)
;


















