--@Autor(es):       Gutiérrez Castillo Oscar, Valderrama Navarro Armando
--@Fecha creación:  01/12/2018
--@Descripción:     <breve descripción del contenido y propósito del archivo>

--Se cosideran dos reglas nuevas:
  --Queremos saber las especiales de los profesores de carreras
  --Queremos saber el puesto de todos los profesores administradores

CREATE GLOBAL TEMPORARY TABLE ESPECIALIDAD_PROFESOR(
  GRADO_ESTUDIO VARCHAR2(2)   NOT NULL,
  NOMBRE        VARCHAR2(50)  NOT NULL,
  AP_PATERNO    VARCHAR2(50)  NOT NULL,
  AP_MATERNO    VARCHAR2(50)  NULL,
  ESPECIALIDAD  VARCHAR2(2)   NOT NULL,
  DESCRIPCION   VARCHAR2(150) NOT NULL
) ON COMMIT PRESERVE ROWS;

INSERT INTO ESPECIALIDAD_PROFESOR (GRADO_ESTUDIO,
  NOMBRE,AP_PATERNO,AP_MATERNO,GRADO_ESTUDIOS_ID,DESCRIPCION)
SELECT GE.CLAVE,P.NOMBRE,P.AP_PATERNO,P.AP_MATERNO,
  q1.ESPECIALIDAD, q1.DESCRIPCION
SELECT FROM PROFESOR P
JOIN GRADO_ESTUDIOS GE
ON GE.GRADO_ESTUDIOS_ID = P.GRADO_ESTUDIOS_ID
JOIN PROFESOR_CARRERA PC
ON PC.PROFESOR_ID = P.PROFESOR_ID
JOIN (
  SELECT E.PROFESOR_CARRERA_ID,GE.CLAVE AS ESPECIALIDAD,
    E.DESCRIPCION AS DESCRIPCION_ESPECIALIDAD
  FROM ESPECIALIDAD E
  JOIN GRADO_ESTUDIOS GE
  ON GE.GRADO_ESTUDIOS_ID = E.GRADO_ESTUDIOS_ID
) q1
ON q1.PROFESOR_CARRERA_ID = PC.PROFESOR_ID


