--@Autor(es):       Gutiérrez Castillo Oscar, Valderrama Navarro Armando
--@Fecha creación:  01/12/2018
--@Descripción:     Creacion de vistas


CREATE OR REPLACE VIEW PROMEDIO_ESTUDIANTE AS
	SELECT E.NUMERO_CUENTA,E.NOMBRE,C.NUM_GRUPO,
		A.NOMBRE,A.CREDITOS,EI.CALIFICACION
	FROM ESTUDIANTE E
	JOIN ESTUDIANTE_INSCRITO EI
	ON E.ESTUDIANTE_ID = EI.ESTUDIANTE_ID
	JOIN CURSO C
	ON C.CURSO_ID = EI.CURSO_ID
	JOIN ASIGNATURA A
	ON A.ASIGNATURA_ID = C.ASIGNATURA_ID;

