--@Autor(es):       Gutiérrez Castillo Oscar, Valderrama Navarro Armando
--@Fecha creación:  01/12/2018
--@Descripción:     <breve descripción del contenido y propósito del archivo>

INSERT INTO DIA_SEMANA(DIA_SEMANA_ID,DESCRIPCION) VALUES (1,'LUNES');
INSERT INTO DIA_SEMANA(DIA_SEMANA_ID,DESCRIPCION) VALUES (2,'MARTES');
INSERT INTO DIA_SEMANA(DIA_SEMANA_ID,DESCRIPCION) VALUES (3,'MIERCOLES');
INSERT INTO DIA_SEMANA(DIA_SEMANA_ID,DESCRIPCION) VALUES (4,'JUEVES');
INSERT INTO DIA_SEMANA(DIA_SEMANA_ID,DESCRIPCION) VALUES (5,'VIERNES');
INSERT INTO DIA_SEMANA(DIA_SEMANA_ID,DESCRIPCION) VALUES (6,'SÁBADO');


INSERT INTO STATUS_TESIS(STATUS_TESIS_ID,CLAVE,DESCRIPCION) VALUES (1,'REGISTRADA','TESIS REGISTRADA');
INSERT INTO STATUS_TESIS(STATUS_TESIS_ID,CLAVE,DESCRIPCION) VALUES (2,'VALIDADA','TESIS VALIDADA, SE SIGNAN SINODALES Y DIRECTOR');
INSERT INTO STATUS_TESIS(STATUS_TESIS_ID,CLAVE,DESCRIPCION) VALUES (3,'CONCLUIDA','TESIS ENTREGADA, EN ESPERA DE RESPUESTA');
INSERT INTO STATUS_TESIS(STATUS_TESIS_ID,CLAVE,DESCRIPCION) VALUES (4,'CANCELADA','TESIS NO APRBADA');
INSERT INTO STATUS_TESIS(STATUS_TESIS_ID,CLAVE,DESCRIPCION) VALUES (5,'CON_CEDULA','TESIS APROBADA, SE ASIANAN CEDULAS PROFESIONALES');


INSERT INTO CARRERA(CARRERA_ID,NOMBRE,CLAVE,DESCRIPCION) VALUES (CARRERA_SEQ.NEXTVAL,'INGENIERIA EN COMPUTACION',001,'LA CARRERA DE INGENIERO EN COMPUTACIÓN TIENE COMO OBJETIVO FORMAR PROFESIONALES CAPACES DE PLANEAR, DISEÑAR, ORGANIZAR, PRODUCIR, OPERAR Y DAR SOPORTE TÉCNICO A LOS SISTEMAS ELECTRÓNICOS PARA EL PROCESAMIENTO DE DATOS, A LOS SISTEMAS DE PROGRAMACIÓN -DE BASE Y DE APLICACIÓN DEL EQUIPO DE CÓMPUTO-, ASÍ COMO EFECTUAR EL CONTROL DIGITAL DE PROCESOS AUTOMÁTICOS.')
INSERT INTO CARRERA(CARRERA_ID,NOMBRE,CLAVE,DESCRIPCION) VALUES (CARRERA_SEQ.NEXTVAL,'INGENIERIA ELECTRICA',002,'LA CARRERA DE INGENIERÍA ELÉCTRICA ELECTRÓNICA TIENE COMO OBJETIVO FORMAR PROFESIONISTAS QUE UTILIZAN LAS CIENCIAS FÍSICAS, QUÍMICAS Y MATEMÁTICAS, ASÍ COMO TÉCNICAS DE INGENIERÍA, ECONOMÍA, COMPUTACIÓN Y ADMINISTRACIÓN PARA TRANSFORMAR LA NATURALEZA MEDIANTE DISPOSITIVOS MECÁNICOS, ELÉCTRICOS Y ELECTRÓNICOS EN BENEFICIO DE LA SOCIEDAD, Y PARA OPTIMAR LA INTEGRACIÓN Y EL FUNCIONAMIENTO DE LOS SISTEMAS PRODUCTIVOS FORMADOS POR HOMBRES, MÁQUINAS E INSUMOS.')
INSERT INTO CARRERA(CARRERA_ID,NOMBRE,CLAVE,DESCRIPCION) VALUES (CARRERA_SEQ.NEXTVAL,'INGENIERIA EN TELECOMUNICACIONES',003,'EL INGENIERO EN TELECOMUNICACIONES ES EL PROFESIONISTA QUE APLICA CONOCIMIENTOS DE LAS CIENCIAS BÁSICAS - FÍSICA Y MATEMÁTICAS-, ASÍ COMO LOS CORRESPONDIENTES A SEÑALES, SISTEMAS, ELECTRÓNICA Y COMPUTACIÓN PARA ANALIZAR, DISEÑAR, PLANEAR, ORGANIZAR, PRODUCIR, INSTALAR, DESARROLLAR, ADEMÁS DE MANTENER EN OPERACIÓN Y ADMINISTRAR REDES Y SISTEMAS DE TELECOMUNICACIONES.')
INSERT INTO CARRERA(CARRERA_ID,NOMBRE,CLAVE,DESCRIPCION) VALUES (CARRERA_SEQ.NEXTVAL,'INGENIERIA MECANICA',004,'LA CARRERA DE INGENIERÍA MECÁNICA FORMA PROFESIONALES QUE, MEDIANTE EL USO DE LA FÍSICA, LA QUÍMICA, LAS MATEMÁTICAS Y LAS TÉCNICAS DE INGENIERÍA, PROPORCIONAN A LA SOCIEDAD HERRAMIENTAS Y BIENES QUE LE PERMITEN APROVECHAR LOS RECURSOS NATURALES PARA SATISFACER LAS NECESIDADES MATERIALES, SOCIALES E INCLUSO INTELECTUALES DEL HOMBRE.')
INSERT INTO CARRERA(CARRERA_ID,NOMBRE,CLAVE,DESCRIPCION) VALUES (CARRERA_SEQ.NEXTVAL,'INGENIERIA CIVIL',005,'EL INGENIERO CIVIL ES EL PROFESIONISTA QUE POSEE UNA FORMACIÓN MULTIDISCIPLINARIA CONFORMADA POR CONOCIMIENTOS GENERALES DE MATEMÁTICAS, FÍSICA, QUÍMICA; Y DE LAS ÁREAS ESPECÍFICAS DE LA DISCIPLINA, LOS QUE AUNADOS A LAS NOCIONES EN COMPUTACIÓN, COMUNICACIÓN GRÁFICA, INFORMÁTICA, ADMINISTRACIÓN Y EVALUACIÓN DE PROYECTOS, LO CAPACITAN PARA PARTICIPAR EN LAS ETAPAS DE PLANEACIÓN, DISEÑO, ORGANIZACIÓN, CONSTRUCCIÓN, OPERACIÓN Y CONSERVACIÓN DE OBRAS CIVILES Y DE INFRAESTRUCTURA.')


INSERT INTO PLAN_ESTUDIOS(PLAN_ESTUDIOS_ID,CLAVE,FECHA_APROBACION,FECHA_TERMINO) VALUES (PLAN_ESTUDIOS_SEQ.NEXTVAL,'PL-2010',TO_DATE('2010-01-01','YYYY-MM-DD'),TO_DATE('2015-12-30','YYYY-MM-DD'));
INSERT INTO PLAN_ESTUDIOS(PLAN_ESTUDIOS_ID,CLAVE,FECHA_APROBACION,FECHA_TERMINO) VALUES (PLAN_ESTUDIOS_SEQ.NEXTVAL,'PL-2016',TO_DATE('2016-01-01','YYYY-MM-DD'),TO_DATE('2020-12-30','YYYY-MM-DD'));

--PLAN DE ESTUDIOS PL-2010--
INSERT INTO ASIGNATURA(ASIGNATURA_ID,CLAVE,NOMBRE,SEMESTRE_CURSAR,CREDITOS,PLAN_ESTUDIOS_ID,
  ASIGNATURA_ANTECEDENTE,SEMESTRE_IMPARTICION) VALUES 
           (ASIGNATURA_SEQ.NEXTVAL,'ALGB','ALGEBRA',1,10,1,
  NULL,NULL);
INSERT INTO ASIGNATURA(ASIGNATURA_ID,CLAVE,NOMBRE,SEMESTRE_CURSAR,CREDITOS,PLAN_ESTUDIOS_ID,
  ASIGNATURA_ANTECEDENTE,SEMESTRE_IMPARTICION) VALUES 
           (ASIGNATURA_SEQ.NEXTVAL,'ALLI','ALGEBRA LINEAL',2,10,1,
  NULL,NULL);
INSERT INTO ASIGNATURA(ASIGNATURA_ID,CLAVE,NOMBRE,SEMESTRE_CURSAR,CREDITOS,PLAN_ESTUDIOS_ID,
  ASIGNATURA_ANTECEDENTE,SEMESTRE_IMPARTICION) VALUES 
           (ASIGNATURA_SEQ.NEXTVAL,'LFYA','LENGUAJES FORMALES Y AUTOMATAS',5,8,1,
  NULL,5);
INSERT INTO ASIGNATURA(ASIGNATURA_ID,CLAVE,NOMBRE,SEMESTRE_CURSAR,CREDITOS,PLAN_ESTUDIOS_ID,
  ASIGNATURA_ANTECEDENTE,SEMESTRE_IMPARTICION) VALUES 
           (ASIGNATURA_SEQ.NEXTVAL,'SO','SISTEMAS OPERATIVOS',6,8,1,
  3,6);
--PLAN DE ESTUDIOS PL-2010--

INSERT INTO ASIGNATURA(ASIGNATURA_ID,CLAVE,NOMBRE,SEMESTRE_CURSAR,CREDITOS,PLAN_ESTUDIOS_ID,
  ASIGNATURA_ANTECEDENTE,SEMESTRE_IMPARTICION) VALUES 
           (ASIGNATURA_SEQ.NEXTVAL,'ALGB','ALGEBRA',1,10,2,
  NULL,NULL);
INSERT INTO ASIGNATURA(ASIGNATURA_ID,CLAVE,NOMBRE,SEMESTRE_CURSAR,CREDITOS,PLAN_ESTUDIOS_ID,
  ASIGNATURA_ANTECEDENTE,SEMESTRE_IMPARTICION) VALUES 
           (ASIGNATURA_SEQ.NEXTVAL,'ALLI','ALGEBRA LINEAL',2,10,2,
  NULL,NULL);
INSERT INTO ASIGNATURA(ASIGNATURA_ID,CLAVE,NOMBRE,SEMESTRE_CURSAR,CREDITOS,PLAN_ESTUDIOS_ID,
  ASIGNATURA_ANTECEDENTE,SEMESTRE_IMPARTICION) VALUES 
           (ASIGNATURA_SEQ.NEXTVAL,'LFYA','LENGUAJES FORMALES Y AUTOMATAS',5,8,2,
  NULL,5);
INSERT INTO ASIGNATURA(ASIGNATURA_ID,CLAVE,NOMBRE,SEMESTRE_CURSAR,CREDITOS,PLAN_ESTUDIOS_ID,
  ASIGNATURA_ANTECEDENTE,SEMESTRE_IMPARTICION) VALUES 
           (ASIGNATURA_SEQ.NEXTVAL,'SO','SISTEMAS OPERATIVOS',6,8,2,
  7,6);


INSERT INTO HORARIO(HORARIO_ID,DIA_IMPARTICION,NUMERO_SALON,NUMERO_CLASE,HORA_INICIO,HORA_FIN) VALUES
                   (HORARIO_SEQ.NEXTVAL,1,'A101',1,TO_DATE('07:00', 'HH24:MM'),TO_DATE('09:00', 'HH24:MM'));
INSERT INTO HORARIO(HORARIO_ID,DIA_IMPARTICION,NUMERO_SALON,NUMERO_CLASE,HORA_INICIO,HORA_FIN) VALUES
                   (HORARIO_SEQ.NEXTVAL,1,'B101',1,TO_DATE('07:00', 'HH24:MM'),TO_DATE('09:00', 'HH24:MM'));
INSERT INTO HORARIO(HORARIO_ID,DIA_IMPARTICION,NUMERO_SALON,NUMERO_CLASE,HORA_INICIO,HORA_FIN) VALUES
                   (HORARIO_SEQ.NEXTVAL,1,'C101',2,TO_DATE('09:00', 'HH24:MM'),TO_DATE('11:00', 'HH24:MM'));
INSERT INTO HORARIO(HORARIO_ID,DIA_IMPARTICION,NUMERO_SALON,NUMERO_CLASE,HORA_INICIO,HORA_FIN) VALUES
                   (HORARIO_SEQ.NEXTVAL,1,'A101',1,TO_DATE('09:00', 'HH24:MM'),TO_DATE('11:00', 'HH24:MM'));


INSERT INTO SEMESTRE(SEMESTRE_ID,ANIO,PERIODO) VALUES
                    (SEMESTRE_SEQ.NEXTVAL,'2011',SEMESTRE_PERIODO_SEQ.NEXTVAL);
INSERT INTO SEMESTRE(SEMESTRE_ID,ANIO,PERIODO) VALUES
                    (SEMESTRE_SEQ.NEXTVAL,'2011',SEMESTRE_PERIODO_SEQ.NEXTVAL);
INSERT INTO SEMESTRE(SEMESTRE_ID,ANIO,PERIODO) VALUES
                    (SEMESTRE_SEQ.NEXTVAL,'2016',SEMESTRE_PERIODO_SEQ.NEXTVAL);
INSERT INTO SEMESTRE(SEMESTRE_ID,ANIO,PERIODO) VALUES
                    (SEMESTRE_SEQ.NEXTVAL,'2016',SEMESTRE_PERIODO_SEQ.NEXTVAL);


INSERT INTO GRADO_ESTUDIOS(GRADO_ESTUDIOS_ID,CLAVE,DESCRIPCION) VALUES (1,'LI','LICENCIATURA');
INSERT INTO GRADO_ESTUDIOS(GRADO_ESTUDIOS_ID,CLAVE,DESCRIPCION) VALUES (2,'MA','MAESTRIA');
INSERT INTO GRADO_ESTUDIOS(GRADO_ESTUDIOS_ID,CLAVE,DESCRIPCION) VALUES (3,'DR','DOCTORADO');


INSERT INTO PUESTO(PUESTO_ID,NOMBRE_PUESTO,DESCRIPCION,PAGO_HORA,HORAS_CUBRIR) VALUES (1,'JEFE DIVISION','COORDINACION DE ACTIVIDADES DE DIVISION, COORDINACION DE BOLSAS DE TRABAJO',100,160);
INSERT INTO PUESTO(PUESTO_ID,NOMBRE_PUESTO,DESCRIPCION,PAGO_HORA,HORAS_CUBRIR) VALUES (2,'SECRETARIO GENERAL','COORDINACION DE ACTIVIDADES DE DIVISION, COORDINACION DE BOLSAS DE TRABAJO, AUXILIAR DE JEFE DE DIVISION',90,160);
INSERT INTO PUESTO(PUESTO_ID,NOMBRE_PUESTO,DESCRIPCION,PAGO_HORA,HORAS_CUBRIR) VALUES (3,'DIRECTOR DE SEMINARIO','COORDINACION DE ACTIVIDADES DE DIVISION, COORDINACION DE BOLSAS DE TRABAJO',70,120);


INSERT INTO PROFESOR(PROFESOR_ID,NOMBRE,AP_PATERNO,AP_MATERNO,RFC,
  CEDULA_PROFESIONAL,GRADO_ESTUDIOS_ID,ES_PROFESOR_ASIGNATURA,ES_PROFESOR_CARRERA,ES_PROFESOR_ADMINISTRADOR) VALUES
                    (PROFESOR_SEQ.NEXTVAL,'LAURA','SANDOVAL','MONTANO','SAMO704532',
  1234567,1,1,0,0);
INSERT INTO PROFESOR(PROFESOR_ID,NOMBRE,AP_PATERNO,AP_MATERNO,RFC,
  CEDULA_PROFESIONAL,GRADO_ESTUDIOS_ID,ES_PROFESOR_ASIGNATURA,ES_PROFESOR_CARRERA,ES_PROFESOR_ADMINISTRADOR) VALUES
                    (PROFESOR_SEQ.NEXTVAL,'JORGE','RODRIGUEZ','CAMPOS','ROCA854532',
  1234567,1,1,0,0);
INSERT INTO PROFESOR(PROFESOR_ID,NOMBRE,AP_PATERNO,AP_MATERNO,RFC,
  CEDULA_PROFESIONAL,GRADO_ESTUDIOS_ID,ES_PROFESOR_ASIGNATURA,ES_PROFESOR_CARRERA,ES_PROFESOR_ADMINISTRADOR) VALUES
                    (PROFESOR_SEQ.NEXTVAL,'JORGE','RODRIGUEZ','CAMPOS','ROCA854532',
  1234567,1,0,1,0);
INSERT INTO PROFESOR(PROFESOR_ID,NOMBRE,AP_PATERNO,AP_MATERNO,RFC,
  CEDULA_PROFESIONAL,GRADO_ESTUDIOS_ID,ES_PROFESOR_ASIGNATURA,ES_PROFESOR_CARRERA,ES_PROFESOR_ADMINISTRADOR) VALUES
                    (PROFESOR_SEQ.NEXTVAL,'JORGE','RODRIGUEZ','CAMPOS','ROCA854532',
  1234567,1,0,1,0);
INSERT INTO PROFESOR(PROFESOR_ID,NOMBRE,AP_PATERNO,AP_MATERNO,RFC,
  CEDULA_PROFESIONAL,GRADO_ESTUDIOS_ID,ES_PROFESOR_ASIGNATURA,ES_PROFESOR_CARRERA,ES_PROFESOR_ADMINISTRADOR) VALUES
                    (PROFESOR_SEQ.NEXTVAL,'JORGE','RODRIGUEZ','CAMPOS','ROCA854532',
  1234567,1,0,0,1);
INSERT INTO PROFESOR(PROFESOR_ID,NOMBRE,AP_PATERNO,AP_MATERNO,RFC,
  CEDULA_PROFESIONAL,GRADO_ESTUDIOS_ID,ES_PROFESOR_ASIGNATURA,ES_PROFESOR_CARRERA,ES_PROFESOR_ADMINISTRADOR) VALUES
                    (PROFESOR_SEQ.NEXTVAL,'JORGE','RODRIGUEZ','CAMPOS','ROCA854532',
  1234567,1,1,0,1);

















